#!/bin/sh

echo "Press any key to START capturing"
read dummy
echo "Capturing..."
./snap a.snap


echo "Press any key to STOP capturing"
read dummy
echo "Capturing..."
./snap b.snap

echo "Diffing..."
ruby diff.rb a.snap b.snap > ab.diff
echo "Analyzing..."
ruby worst.rb < ab.diff
