#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Press any key to START capturing"
read dummy
echo "Taking snapshot..."
"$DIR/snap" a.snap


echo "Press any key to STOP capturing"
read dummy
echo "Taking snapshot..."
"$DIR/snap" b.snap

echo "Diffing..."
ruby "$DIR/diff.rb" a.snap b.snap > ab.diff
echo "Analyzing..."
ruby "$DIR/worst.rb" < ab.diff
